db:
  image: mongo
  ports:
    - "27017:27017"
  command: "--smallfiles --logpath=/dev/null"
services:
  image: cesaregb/base_services
  command: mvn compile exec:java
  ports:
    - "8080:8080"
  env_file:
    - ./common.env
web:
  image: cesaregb/process-admin
  command: npm start
  volumes:
    - "./node_app:/myapp"
  ports:
    - "9000:9000"
  links:
    - "db:mongo"
    - "services:services"
  env_file:
    - ./common.env
